collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.9242749
color:
  saturation: 0.3915145
  brandStrength: 0.7943072
  lightness: 0.3393406
  brandColors:
    - '#0B0D08'
    - '#C1C5E0'
    - '#FFFFFF'
    - '#9395C5'
    - '#453B3A'
  rhythmicContrast: 0.9631737
layout_spectrum: 1
name: GauMedia
